name: FastAPI test on push

on:
  pull_request:
    branches: ["main"]
  push:

jobs:
  test:
    name: python
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: social-test      
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
    steps:        
      - uses: actions/checkout@v4

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev
        
      - name: Run tests
        run: |
          cd backend
          uv run pytest
        env:  
            TEST_DB_USERNAME: postgres
            TEST_DB_PASSWORD: postgres
            TEST_DB_HOST: localhost
            TEST_DB_PORT: 5432
            TEST_DB_NAME: social-test

            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_HOST: localhost
            DB_PORT: 5432
            DB_NAME: social-test
