name: FastAPI test on push

on:
  pull_request:
    branches: ["main"]
  push:

jobs:
  test:
    name: python
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: social-test      
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ENV_FILE: .env.actions
      
    steps:        
      - uses: actions/checkout@v4

      - name: Enable caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Import .env.actions
        id: import-env
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ${{ env.ENV_FILE }}
        
      - name: Run tests
        run: |
          cd backend
          uv run pytest
